In [1]:
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [3]:
df=pd.read_csv(r"C:\Users\Sejal\Desktop\ML\car_price_prediction.csv")

df.head()

ID  Price  Levy Manufacturer    Model  Prod. year   Category  \
0  45654403  13328  1399        LEXUS   RX 450        2010       Jeep   
1  44731507  16621  1018    CHEVROLET  Equinox        2011       Jeep   
2  45774419   8467     -        HONDA      FIT        2006  Hatchback   
3  45769185   3607   862         FORD   Escape        2011       Jeep   
4  45809263  11726   446        HONDA      FIT        2014  Hatchback   

  Leather interior Fuel type Engine volume    Mileage  Cylinders  \
0              Yes    Hybrid           3.5  186005 km          6   
1               No    Petrol             3  192000 km          6   
2               No    Petrol           1.3  200000 km          4   
3              Yes    Hybrid           2.5  168966 km          4   
4              Yes    Petrol           1.3   91901 km          4   

  Gear box type Drive wheels  Doors             Wheel   Color  Airbags  
0     Automatic          4x4  4-May        Left wheel  Silver       12  
1     Tiptronic          4x4  4-May        Left wheel   Black        8  
2      Variator        Front  4-May  Right-hand drive   Black        2  
3     Automatic          4x4  4-May        Left wheel   White        0  
4     Automatic        Front  4-May        Left wheel  Silver        4

In [4]:
df['Mileage']=df['Mileage'].str.replace("km","")
df['Doors']=df['Doors'].str.replace("May","")
df['Engine volume']=df['Engine volume'].str.replace("Turbo","")
df['Levy']=df['Levy'].replace("-",np.NaN)


In [60]:
df[['Manufacturer','Category','Model','Fuel type','Gear box type','Color','Wheel','Drive wheels','Leather interior','Doors']]=df[['Manufacturer','Category','Model','Fuel type','Gear box type','Color','Wheel','Drive wheels','Leather interior','Doors']].apply(LabelEncoder().fit_transform)
df.head(10)

ID  Price  Levy  Manufacturer  Model  Prod. year  Category  \
0  45654403  13328  1399            32   1242        2010         4   
1  44731507  16621  1018             8    658        2011         4   
2  45774419   8467   NaN            21    684        2006         3   
3  45769185   3607   862            16    661        2011         4   
4  45809263  11726   446            21    684        2014         3   
5  45802912  39493   891            23   1305        2016         4   
6  45656768   1803   761            58   1154        2010         3   
7  45816158    549   751            23   1334        2013         9   
8  45641395   1098   394            58    435        2014         9   
9  45756839  26657   NaN            32   1235        2007         4   

   Leather interior  Fuel type Engine volume  Mileage  Cylinders  \
0                 1          2           3.5  186005           6   
1                 0          5             3  192000           6   
2                 0          5           1.3  200000           4   
3                 1          2           2.5  168966           4   
4                 1          5           1.3   91901           4   
5                 1          1             2  160931           4   
6                 1          2           1.8  258909           4   
7                 1          5           2.4  216118           4   
8                 1          2           2.5  398069           4   
9                 1          5           3.5  128500           6   

   Gear box type  Drive wheels  Doors  Wheel  Color  Airbags  
0              0             0      1      0     12       12  
1              2             0      1      0      1        8  
2              3             1      1      1      1        2  
3              0             0      1      0     14        0  
4              0             1      1      0     12        4  
5              0             1      1      0     14        4  
6              0             1      1      0     14       12  
7              0             1      1      0      7       12  
8              0             1      1      0      1       12  
9              0             0      1      0     12       12

In [61]:
from sklearn.impute import SimpleImputer
im_mean=SimpleImputer(missing_values=np.NaN,strategy='mean')
df[['Levy']]=im_mean.fit_transform(df[['Levy']])
df.head(15)

ID  Price         Levy  Manufacturer  Model  Prod. year  Category  \
0   45654403  13328  1399.000000            32   1242        2010         4   
1   44731507  16621  1018.000000             8    658        2011         4   
2   45774419   8467   906.838128            21    684        2006         3   
3   45769185   3607   862.000000            16    661        2011         4   
4   45809263  11726   446.000000            21    684        2014         3   
5   45802912  39493   891.000000            23   1305        2016         4   
6   45656768   1803   761.000000            58   1154        2010         3   
7   45816158    549   751.000000            23   1334        2013         9   
8   45641395   1098   394.000000            58    435        2014         9   
9   45756839  26657   906.838128            32   1235        2007         4   
10  45621750    941  1053.000000            36    601        2014         9   
11  45814819   8781   906.838128            16   1421        1999         6   
12  45815568   3000   906.838128            42   1457        1997         2   
13  45661288   1019  1055.000000            32   1242        2013         4   
14  45732604  59464   891.000000            23   1305        2016         4   

    Leather interior  Fuel type Engine volume  Mileage  Cylinders  \
0                  1          2           3.5  186005           6   
1                  0          5             3  192000           6   
2                  0          5           1.3  200000           4   
3                  1          2           2.5  168966           4   
4                  1          5           1.3   91901           4   
5                  1          1             2  160931           4   
6                  1          2           1.8  258909           4   
7                  1          5           2.4  216118           4   
8                  1          2           2.5  398069           4   
9                  1          5           3.5  128500           6   
10                 1          1           3.5  184467           6   
11                 0          0             4       0           8   
12                 0          0           1.6  350000           4   
13                 1          2           3.5  138038           6   
14                 1          1             2   76000           4   

    Gear box type  Drive wheels  Doors  Wheel  Color  Airbags  
0               0             0      1      0     12       12  
1               2             0      1      0      1        8  
2               3             1      1      1      1        2  
3               0             0      1      0     14        0  
4               0             1      1      0     12        4  
5               0             1      1      0     14        4  
6               0             1      1      0     14       12  
7               0             1      1      0      7       12  
8               0             1      1      0      1       12  
9               0             0      1      0     12       12  
10              0             2      1      0     14       12  
11              1             2      0      0      2        0  
12              1             1      1      0     14        4  
13              0             1      1      0     14       12  
14              0             1      1      0     14        4

In [15]:
x=df.iloc[:,3:].values
y=df.iloc[:,1:2].values
print(x);
print(y);

[[32 1242 2010 ... 0 12 12]
 [8 658 2011 ... 0 1 8]
 [21 684 2006 ... 1 1 2]
 ...
 [23 1442 2010 ... 0 7 4]
 [8 456 2007 ... 0 1 4]
 [23 1334 2012 ... 0 14 12]]
[[13328]
 [16621]
 [ 8467]
 ...
 [26108]
 [ 5331]
 [  470]]


In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=2)

In [27]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
x=sc.fit_transform(x)
y=sc.fit_transform(y)
print(x)
y

[[0.5        0.78162366 0.87654321 ... 0.         0.8        0.75      ]
 [0.125      0.41409692 0.88888889 ... 0.         0.06666667 0.5       ]
 [0.328125   0.43045941 0.82716049 ... 1.         0.06666667 0.125     ]
 ...
 [0.359375   0.90748899 0.87654321 ... 0.         0.46666667 0.25      ]
 [0.125      0.28697294 0.83950617 ... 0.         0.06666667 0.25      ]
 [0.359375   0.83952171 0.90123457 ... 0.         0.93333333 0.75      ]]


array([[5.06585594e-04],
       [6.31759028e-04],
       [3.21809382e-04],
       ...,
       [9.92378637e-04],
       [2.02603828e-04],
       [1.78276164e-05]])

In [18]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [22]:
y_pred = regressor.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[27684.48230936   100.        ]
 [15361.63299364 25889.        ]
 [32521.06292461 29166.        ]
 ...
 [ 5080.05231669  8781.        ]
 [10550.74258814  3763.        ]
 [11555.38513072   470.        ]]


In [23]:
from sklearn.neighbors import KNeighborsClassifier
c=KNeighborsClassifier(n_neighbors=3,metric='minkowski',p=1)
c.fit(x_train,y_train)



C:\Users\Sejal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3, p=1)

In [25]:
y_pred=c.predict(x_test)
print(y_pred)
print(y_test)


[11133   627  9408 ...  7840  4547   470]
[[  100]
 [25889]
 [29166]
 ...
 [ 8781]
 [ 3763]
 [  470]]


In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)
#print(classification_report(y_test,y_pred))
print(cm)
print(ac)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0.19074844074844075


In [ ]:
from sklearn import metrics
m=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=[False,True])
m.plot()
m.show()

In [ ]:
%matplotlib inline
import seaborn as sns
sns.heatmap(confusion_matrix(y_test, y_pred),annot=True)