In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\Sejal\Desktop\ML\CAR DETAILS FROM CAR DEKHO.csv")
df.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [4]:
n=df.isnull().sum()


name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [5]:
lb=LabelEncoder()
df[['name','fuel','seller_type','transmission','owner']]=df[['name','fuel','seller_type','transmission','owner']].apply(LabelEncoder().fit_transform)

In [7]:
df.tail()

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
4335   602  2014         409999      80000     1            1             1   
4336   601  2014         409999      80000     1            1             1   
4337   777  2009         110000      83000     4            1             1   
4338   381  2016         865000      90000     1            1             1   
4339  1154  2016         225000      40000     4            1             1   

      owner  
4335      2  
4336      2  
4337      2  
4338      0  
4339      0

In [9]:
x=df.iloc[:,[0,1,3,4,5,6,7]].values
y=df.iloc[:,2:].values
print(x)
print(y)

[[   775   2007  70000 ...      1      1      0]
 [  1041   2007  50000 ...      1      1      0]
 [   505   2012 100000 ...      1      1      0]
 ...
 [   777   2009  83000 ...      1      1      2]
 [   381   2016  90000 ...      1      1      0]
 [  1154   2016  40000 ...      1      1      0]]
[[ 60000  70000      4      1      1      0]
 [135000  50000      4      1      1      0]
 [600000 100000      1      1      1      0]
 ...
 [110000  83000      4      1      1      2]
 [865000  90000      1      1      1      0]
 [225000  40000      4      1      1      0]]


In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [11]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
y_train=sc.fit_transform(y_train)

In [12]:
from sklearn.linear_model import LinearRegression
lg=LinearRegression()
lg.fit(x_train,y_train)

LinearRegression()

In [13]:
y_pred=lg.predict(x_test)
y_pred

array([[-9.40556162e+03,  1.20000000e+05,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  6.58496047e-14],
       [-4.44733140e+03,  6.00000000e+04,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00, -3.47612523e-13],
       [-6.38912036e+02,  1.40000000e+04,  4.00000000e+00,
         1.25245340e-12,  1.00000000e+00, -4.79309949e-13],
       ...,
       [-2.39119552e+03,  3.50000000e+04,  4.00000000e+00,
         1.00000000e+00,  1.00000000e+00, -7.55085896e-13],
       [-5.26084187e+03,  7.00000000e+04,  4.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  2.00000000e+00],
       [-7.76390182e+03,  1.00000000e+05,  4.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  2.00000000e+00]])

In [14]:
lg.coef_

array([[-2.64280069e-02,  2.62151325e-01, -8.26397777e-02,
        -2.38157387e-01, -1.56407145e-02, -4.59082384e-01,
        -3.71395041e-02],
       [ 2.66567859e-16, -6.66133815e-16,  1.00000000e+00,
         6.93889390e-16, -1.22124533e-15,  8.88178420e-16,
        -2.02615702e-15],
       [ 5.49997233e-16, -9.43689571e-16,  1.05471187e-15,
         1.00000000e+00, -6.66133815e-16, -1.24900090e-16,
        -1.64451786e-15],
       [ 7.80932553e-17,  2.22044605e-16,  5.55111512e-17,
        -3.05311332e-16,  1.00000000e+00,  1.16573418e-15,
        -2.49800181e-16],
       [-5.32444148e-16,  3.88578059e-16, -1.94289029e-16,
        -7.77156117e-16,  1.13797860e-15,  1.00000000e+00,
         2.01227923e-16],
       [-6.76243378e-16, -1.66533454e-16,  6.93889390e-18,
        -6.93889390e-18,  2.34534614e-15, -2.49106291e-15,
         1.00000000e+00]])

In [15]:
lg.intercept_

array([ 5.81720038e-15, -1.49883572e-29, -2.16967564e-29,  5.62063395e-30,
        7.69139383e-30, -6.50810247e-30])

In [17]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
m=mean_absolute_error(y_pred,y_test)
ms=mean_squared_error(y_pred,y_test)
r2s=r2_score(y_pred,y_test)
print(m)
print(ms)
print(r2s)

85191.76295814478
89643390037.60443
-6650.1009292755725
